/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/0vAENLjbEFv
 */
import { Button } from "@/components/ui/button"
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"
import { Input } from "@/components/ui/input"

export function MainPage() {
  return (
    (<div className="min-h-screen bg-gray-200 p-4">
      <header className="flex justify-between items-center p-4 bg-gray-300">
        <div className="bg-white p-2 rounded">
          <span className="font-bold">LOGO</span>
        </div>
        <div className="space-x-2">
          <Button className="bg-white rounded-lg">login</Button>
          <Button className="bg-black text-white rounded-lg">Register</Button>
        </div>
      </header>
      <main className="flex justify-between items-start mt-8">
        <div className="w-2/3 bg-white p-4 rounded">
          <Select>
            <SelectTrigger id="hash-generation">
              <SelectValue placeholder="<Hash value>: <generation>" />
            </SelectTrigger>
            <SelectContent position="popper">
              <SelectItem value="hash1">Hash1: Generation1</SelectItem>
              <SelectItem value="hash2">Hash2: Generation2</SelectItem>
              <SelectItem value="hash3">Hash3: Generation3</SelectItem>
            </SelectContent>
          </Select>
          <div className="mt-4">
            <Button
              className="w-full flex justify-center items-center bg-gray-100 text-gray-600 rounded-lg">
              <PlusIcon className="h-5 w-5" />
              Generate new...
            </Button>
          </div>
        </div>
        <div className="w-1/3 ml-8">
          <div className="bg-white p-4 mb-4 rounded">
            <Button className="w-full">make new Hash</Button>
          </div>
          <div className="bg-white p-4 rounded">
            <Input placeholder="Hash Key input" type="text" />
          </div>
        </div>
      </main>
    </div>)
  );
}


function PlusIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>)
  );
}
